FROM dunglas/frankenphp:latest-php8.2

RUN install-php-extensions \
    pdo_mysql \
    pdo_pgsql \
    intl \
    opcache \
    zip \
    apcu \
    redis \
    bcmath \
    xdebug

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
