-- Entity: App\Entity\InboundException
-- Description: Inbound quality/quantity exceptions

CREATE TABLE `inbound_exceptions` (
    `id` VARCHAR(26) NOT NULL PRIMARY KEY COMMENT 'ULID',
    `exceptionNo` VARCHAR(32) NOT NULL UNIQUE COMMENT 'Exception number (EX...)',
    `inbound_order_id` VARCHAR(26) NOT NULL,
    `merchant_id` VARCHAR(26) NOT NULL,
    `warehouse_id` VARCHAR(26) NOT NULL,
    `type` VARCHAR(30) NOT NULL COMMENT 'quantity_short, quantity_over, damaged, wrong_item, quality_issue, packaging, expired, other',
    `status` VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT 'pending, processing, resolved, closed',
    `items` JSON NOT NULL COMMENT 'Exception items array',
    `totalExpectedQuantity` INT NOT NULL DEFAULT 0,
    `totalActualQuantity` INT NOT NULL DEFAULT 0,
    `differenceQuantity` INT NOT NULL DEFAULT 0,
    `description` TEXT NOT NULL,
    `evidenceImages` JSON NULL COMMENT 'Evidence image URLs',
    `resolution` VARCHAR(30) NULL COMMENT 'accept, reject, claim, recount, partial_accept',
    `resolutionNotes` TEXT NULL,
    `claimAmount` DECIMAL(10,2) NULL,
    `resolvedAt` DATETIME NULL,
    `communicationLog` JSON NULL COMMENT 'Communication history',
    `reportedBy` VARCHAR(26) NULL COMMENT 'Reporter user ID',
    `resolvedBy` VARCHAR(26) NULL COMMENT 'Resolver user ID',
    `createdAt` DATETIME NOT NULL,
    `updatedAt` DATETIME NOT NULL,
    INDEX `idx_inbound_exc_no` (`exceptionNo`),
    INDEX `idx_inbound_exc_order` (`inbound_order_id`),
    INDEX `idx_inbound_exc_merchant` (`merchant_id`),
    INDEX `idx_inbound_exc_status` (`status`),
    INDEX `idx_inbound_exc_created` (`createdAt`),
    CONSTRAINT `fk_inbound_exc_order` FOREIGN KEY (`inbound_order_id`) REFERENCES `inbound_orders` (`id`),
    CONSTRAINT `fk_inbound_exc_merchant` FOREIGN KEY (`merchant_id`) REFERENCES `merchants` (`id`),
    CONSTRAINT `fk_inbound_exc_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Inbound exceptions';