-- Entity: App\Entity\Order
-- Description: Orders synced from sales channels

CREATE TABLE `orders` (
    `id` VARCHAR(26) NOT NULL PRIMARY KEY COMMENT 'ULID',
    `order_no` VARCHAR(30) NOT NULL UNIQUE COMMENT 'Platform order number',
    `sales_channel_id` VARCHAR(26) NOT NULL,
    `external_order_id` VARCHAR(100) NOT NULL COMMENT 'Channel order ID',
    `external_order_no` VARCHAR(100) NULL COMMENT 'Channel order number',
    `receiver_name` VARCHAR(50) NOT NULL,
    `receiver_phone` VARCHAR(30) NOT NULL,
    `receiver_province` VARCHAR(50) NULL,
    `receiver_city` VARCHAR(50) NULL,
    `receiver_district` VARCHAR(50) NULL,
    `receiver_address` VARCHAR(500) NOT NULL,
    `receiver_postal_code` VARCHAR(20) NULL,
    `total_amount` DECIMAL(12,2) NOT NULL,
    `product_amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    `shipping_amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `discount_amount` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    `currency` VARCHAR(3) NOT NULL DEFAULT 'CNY',
    `status` VARCHAR(30) NOT NULL DEFAULT 'pending' COMMENT 'pending, allocating, allocated, allocation_failed, fulfilling, shipped, delivered, completed, cancelled',
    `payment_status` VARCHAR(30) NOT NULL DEFAULT 'pending' COMMENT 'pending, paid, refunded, partial_refunded',
    `placed_at` DATETIME NOT NULL COMMENT 'Order placed time',
    `paid_at` DATETIME NULL,
    `allocated_at` DATETIME NULL,
    `shipped_at` DATETIME NULL,
    `delivered_at` DATETIME NULL,
    `completed_at` DATETIME NULL,
    `cancelled_at` DATETIME NULL,
    `buyer_remark` TEXT NULL,
    `seller_remark` TEXT NULL,
    `allocation_fail_reason` TEXT NULL,
    `synced_at` DATETIME NOT NULL COMMENT 'Sync time',
    `external_data` JSON NULL COMMENT 'Raw order data',
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NOT NULL,
    INDEX `idx_order_channel` (`sales_channel_id`),
    INDEX `idx_order_status` (`status`),
    INDEX `idx_order_external` (`external_order_id`),
    INDEX `idx_order_placed` (`placed_at`),
    CONSTRAINT `fk_order_channel` FOREIGN KEY (`sales_channel_id`) REFERENCES `sales_channels` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Orders';