-- Entity: App\Entity\OutboundOrder
-- Description: Outbound orders for platform warehouse (WMS integration)

CREATE TABLE `outbound_orders` (
    `id` VARCHAR(26) NOT NULL PRIMARY KEY COMMENT 'ULID',
    `outbound_no` VARCHAR(30) NOT NULL UNIQUE,
    `fulfillment_id` VARCHAR(26) NULL,
    `warehouse_id` VARCHAR(26) NOT NULL,
    `outbound_type` VARCHAR(30) NOT NULL DEFAULT 'sales' COMMENT 'sales, return_to_merchant, transfer, scrap',
    `status` VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT 'pending, picking, packing, ready, shipped, cancelled',
    `sync_status` VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT 'pending, synced, failed, callback',
    `external_id` VARCHAR(100) NULL COMMENT 'WMS outbound ID',
    `sync_error` TEXT NULL,
    `sync_attempts` INT NOT NULL DEFAULT 0,
    `synced_at` DATETIME NULL,
    `last_sync_at` DATETIME NULL,
    `receiver_name` VARCHAR(50) NOT NULL,
    `receiver_phone` VARCHAR(30) NOT NULL,
    `receiver_address` VARCHAR(500) NOT NULL,
    `receiver_postal_code` VARCHAR(20) NULL,
    `shipping_carrier` VARCHAR(50) NULL,
    `tracking_number` VARCHAR(100) NULL,
    `picking_started_at` DATETIME NULL,
    `picking_completed_at` DATETIME NULL,
    `packing_started_at` DATETIME NULL,
    `packing_completed_at` DATETIME NULL,
    `shipped_at` DATETIME NULL,
    `cancelled_at` DATETIME NULL,
    `cancel_reason` TEXT NULL,
    `remark` TEXT NULL,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NOT NULL,
    INDEX `idx_outbound_fulfillment` (`fulfillment_id`),
    INDEX `idx_outbound_warehouse` (`warehouse_id`),
    INDEX `idx_outbound_status` (`status`),
    INDEX `idx_outbound_sync_status` (`sync_status`),
    INDEX `idx_outbound_external` (`external_id`),
    CONSTRAINT `fk_outbound_fulfillment` FOREIGN KEY (`fulfillment_id`) REFERENCES `fulfillments` (`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_outbound_warehouse` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Outbound orders';